#
# StatTrackers
# by Auxilor
#

reset-on-apply: false # Reset stat on apply
hide-attributes: true # Add HIDE_ATTRIBUTES flag to all tracker items

stat:
  damage_dealt:
    name: "Damage dealt"
    color: "&b"
    tracker:
      item: compass
      recipe:
        - iron_sword
        - iron_sword
        - iron_sword

        - iron_sword
        - compass
        - iron_sword

        - iron_sword
        - iron_sword
        - iron_sword

  criticals_dealt:
    name: "Criticals dealt"
    color: "&b"
    tracker:
      item: compass
      recipe:
        - iron_sword
        - obsidian
        - iron_sword

        - obsidian
        - compass
        - obsidian

        - iron_sword
        - obsidian
        - iron_sword

  arrows_shot:
    name: "Arrows shot"
    color: "&b"
    tracker:
      item: compass
      recipe:
        - air
        - arrow
        - air

        - arrow
        - compass
        - arrow

        - air
        - arrow
        - air

  blocks_broken:
    name: "Blocks broken"
    color: "&b"
    tracker:
      item: compass
      recipe:
        - iron_pickaxe
        - iron_pickaxe
        - iron_pickaxe

        - iron_pickaxe
        - compass
        - iron_pickaxe

        - iron_pickaxe
        - iron_pickaxe
        - iron_pickaxe

  damage_blocked:
    name: "Damage blocked"
    color: "&b"
    tracker:
      item: compass
      recipe:
        - air
        - shield
        - air

        - shield
        - compass
        - shield

        - air
        - shield
        - air

  damage_taken:
    name: "Damage taken while wearing"
    color: "&b"
    tracker:
      item: compass
      recipe:
        - air
        - iron_helmet
        - air

        - iron_chestplate
        - compass
        - iron_leggings

        - air
        - iron_boots
        - air

  distance_flown:
    name: "Distance Flown"
    color: "&b"
    tracker:
      item: compass
      recipe:
        - air
        - phantom_membrane
        - air

        - phantom_membrane
        - compass
        - phantom_membrane

        - air
        - phantom_membrane
        - air

  distance_sneaked:
    name: "Distance sneaked"
    color: "&b"
    tracker:
      item: compass
      recipe:
        - air
        - leather_boots
        - air

        - leather_boots
        - compass
        - leather_boots

        - air
        - leather_boots
        - air

  distance_jumped:
    name: "Distance jumped"
    color: "&b"
    tracker:
      item: compass
      recipe:
        - slime_ball
        - leather_boots
        - slime_ball

        - leather_boots
        - compass
        - leather_boots

        - slime_ball
        - leather_boots
        - slime_ball

  distance_sprinted:
    name: "Distance sprinted"
    color: "&b"
    tracker:
      item: compass
      recipe:
        - air
        - golden_boots
        - air

        - golden_boots
        - compass
        - golden_boots

        - air
        - golden_boots
        - air

  item_damage:
    name: "Total damage"
    color: "&b"
    tracker:
      item: compass
      recipe:
        - air
        - air
        - air

        - anvil
        - compass
        - anvil

        - air
        - air
        - air

  mobs_killed:
    name: "Mobs killed"
    color: "&b"
    tracker:
      item: compass
      recipe:
        - air
        - rotten_flesh
        - air

        - bone
        - compass
        - string

        - air
        - gunpowder
        - air

  players_killed:
    name: "Players killed"
    color: "&b"
    tracker:
      item: compass
      recipe:
        - diamond_sword
        - diamond_sword
        - diamond_sword

        - diamond_sword
        - compass
        - diamond_sword

        - diamond_sword
        - diamond_sword
        - diamond_sword

  times_jumped:
    name: "Times jumped while wearing"
    color: "&b"
    tracker:
      item: compass
      recipe:
        - air
        - slime_ball
        - air

        - slime_ball
        - compass
        - slime_ball

        - air
        - slime_ball
        - air

  experience_absorbed:
    name: "Experience gained while wearing"
    color: "&b"
    tracker:
      item: compass
      recipe:
        - air
        - emerald
        - air

        - emerald
        - compass
        - emerald

        - air
        - emerald
        - air

  bosses_killed:
    name: "Bosses killed"
    color: "&b"
    tracker:
      item: compass
      recipe:
        - air
        - air
        - air

        - dragon_head
        - compass
        - dragon_head

        - air
        - air
        - air

  distance_travelled:
    name: "Distance Travelled"
    color: "&b"
    tracker:
      item: compass
      recipe:
        - air
        - paper
        - air

        - paper
        - compass
        - paper

        - air
        - paper
        - air

  headshots:
    name: "Headshots"
    color: "&b"
    tracker:
      item: compass
      recipe:
        - air
        - bow
        - air

        - bow
        - compass
        - bow

        - air
        - bow
        - air
