#
# ItemStats
# by Auxilor
#

stat:
  damage_dealt:
    name: "Damage dealt"
    color: "&b"
    enabled: true
    tracker-recipe:
      - iron_sword
      - iron_sword
      - iron_sword

      - iron_sword
      - compass
      - iron_sword

      - iron_sword
      - iron_sword
      - iron_sword


  arrows_shot:
    name: "Arrows shot"
    color: "&b"
  blocks_broken:
    name: "Blocks broken"
    color: "&b"
  damage_blocked:
    name: "Damage blocked"
    color: "&b"
  damage_taken:
    name: "Damage taken while wearing"
    color: "&b"
  distance_flown:
    name: "Distance Flown"
    color: "&b"
  distance_sneaked:
    name: "Distance sneaked"
    color: "&b"
  distance_sprinted:
    name: "Distance sprinted"
    color: "&b"
  item_damage:
    name: "Total damage"
    color: "&b"
  mobs_killed:
    name: "Mobs killed"
    color: "&b"
  players_killed:
    name: "Players killed"
    color: "&b"
  times_jumped:
    name: "Times jumped while wearing"
    color: "&b"
  experience_absorbed:
    name: "Experience gained while wearing"
    color: "&b"
  bosses_killed:
    name: "Bosses killed"
    color: "&b"
  distance_travelled:
    name: "Distance Travelled"
    color: "&b"
  headshots:
    name: "Headshots"
    color: "&b"