name: StatTrackers
version: ${projectVersion}
main: com.willfp.stattrackers.StatTrackersPlugin
api-version: 1.15
authors: [ Auxilor ]
website: willfp.com
load: STARTUP
depend:
  - eco
  - ProtocolLib
softdepend:
  - WorldGuard
  - GriefPrevention
  - Towny
  - FactionsUUID
  - Lands
  - Kingdoms
  - NoCheatPlus
  - AAC
  - Matrix
  - Spartan
  - PlaceholderAPI
  - mcMMO

commands:
  stattrackers:
    description: Base plugin config
    permission: stattrackers.command.stattrackeres

permissions:
  stattrackers.*:
    description: All stattrackers permissions
    default: op
    children:
      stattrackers.command.reload: true
      stattrackers.command.activestat: true
      stattrackers.command.give: true
      stattrackers.command.stattrackers: true

  stattrackers.command.stattrackers:
    description: Allows using the base command
    default: true
  stattrackers.command.reload:
    description: Allows reloading the config
    default: op
  stattrackers.command.activestat:
    description: Allows the use of /stattrackers activestat to set the stat displayed on an item
    default: op
  stattrackers.command.give:
    description: Allows the use of /stattrackers give to give a player a stat tracker
    default: op