name: ItemStats
version: ${projectVersion}
main: com.willfp.itemstats.ItemStatsPlugin
api-version: 1.15
authors: [ Auxilor ]
website: willfp.com
load: STARTUP
depend:
  - eco
  - ProtocolLib
softdepend:
  - WorldGuard
  - GriefPrevention
  - Towny
  - FactionsUUID
  - Lands
  - Kingdoms
  - NoCheatPlus
  - AAC
  - Matrix
  - Spartan
  - PlaceholderAPI
  - mcMMO

commands:
  istatsreload:
    description: Reloads config
    permission: itemstats.reload
  activestat:
    description: Sets the active stat on an item
    permission: itemstats.activestat
  istatsgive:
    description: Gives a player a stat tracker
    permission: itemstats.give

permissions:
  itemstats.*:
    description: All itemstats permissions
    default: op
    children:
      itemstats.reload: true
      itemstats.activestat: true

  itemstats.reload:
    description: Allows reloading the config
    default: op
  itemstats.activestat:
    description: Allows the use of /activestat to set the stat displayed on an item
    default: true
  itemstats.give:
    description: Allows the use of /istatsgive to give a player a stat tracker
    default: true