name: StatTrackers
version: ${projectVersion}
main: com.willfp.stattrackers.StatTrackersPlugin
api-version: 1.15
authors: [ Auxilor ]
website: willfp.com
load: STARTUP
depend:
  - eco
  - ProtocolLib
softdepend:
  - WorldGuard
  - GriefPrevention
  - Towny
  - FactionsUUID
  - Lands
  - Kingdoms
  - NoCheatPlus
  - AAC
  - Matrix
  - Spartan
  - PlaceholderAPI
  - mcMMO

commands:
  streload:
    description: Reloads config
    permission: stattrackers.reload
  activestat:
    description: Sets the active stat on an item
    permission: stattrackers.activestat
  stgive:
    description: Gives a player a stat tracker
    permission: stattrackers.give

permissions:
  stattrackers.*:
    description: All stattrackers permissions
    default: op
    children:
      stattrackers.reload: true
      stattrackers.activestat: true

  stattrackers.reload:
    description: Allows reloading the config
    default: op
  stattrackers.activestat:
    description: Allows the use of /activestat to set the stat displayed on an item
    default: op
  stattrackers.give:
    description: Allows the use of /stgive to give a player a stat tracker
    default: op