name: ItemStats
version: ${projectVersion}
main: com.willfp.itemstats.ItemStatsPlugin
api-version: 1.15
authors: [ Auxilor ]
website: willfp.com
load: STARTUP
depend:
  - ProtocolLib
softdepend:
  - WorldGuard
  - GriefPrevention
  - Towny
  - FactionsUUID
  - Lands
  - Kingdoms
  - NoCheatPlus
  - AAC
  - Matrix
  - Spartan
  - PlaceholderAPI
  - mcMMO

commands:
  istatsreload:
    description: Reloads config
    permission: itemstats.reload
  istatsdebug:
    description: Debug information
    permission: itemstats.istatsdebug

permissions:
  itemstats.*:
    description: All itemstats permissions
    default: op
    children:
      itemstats.reload: true
      itemstats.istatsdebug: true

  itemstats.reload:
    description: Allows reloading the config
    default: op
  itemstats.istatsdebug:
    description: Allows the use of /istatsdebug to print verbose debug information to console
    default: op